version: "3.9"
services:
  mongobd:
    image: mongo:4.4.6
    container_name: meu-mongo
    networks:
      - compose-bridge
  
  alurabook:
    image: aluradocker/alura-books:1.0
    container_name: alurabooks
    networks:
      - compose-bridge
    ports:
      - 2000:3000

networks:
  compose-bridge:
    driver: bridge